title: Steven Mineros # your name (or website title) here
logo: "/images/AmatSteven.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This is my portfolio 
  <br><br>
  Please contact me if you'd like me to create a website for you or your company.  
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
